### ISSUE TITLE
Disable HTTPS for integration testing

### ISSUE THREAD

**Issue by 1gor** [goblindegook/wp-cas-server#16]
Would it be possible to have an option of not enforcing `https` ? When developing the integration of Cassava with some external apps it is not always practical to set up a https server.

For example, wrap the following in some environment variable check?

```
// from /lib/CAS/Server.php
if ( ! \is_ssl()  && getenv("DELOPMENT_MODE_IS_ON") !== false ) {
            throw new GeneralException(
                __( 'The CAS server requires SSL.', 'wp-cas-server' ) );
        }
```

as well as

```
// from /lib/Admin.php
public function admin_notices() {
        if ( ! \is_ssl() && \current_user_can( 'install_plugins' )  && getenv("DELOPMENT_MODE_IS_ON") !== false) {
            $this->adminNoticeNoSSL();
        }
    }
```

**Comment by goblindegook** [comment]
The best way to do this would be to configure your development WordPress server to use a self-signed certificate. If you use something like VVV, one is given to you out of the box.

If you still need to force Cassava to serve requests over HTTP, you can fool WordPress into assuming it's on HTTPS through existing hooks. For example:

``` php
add_action( 'cas_server_before_request', function () {
    if ( defined( 'WP_ENV' ) && WP_ENV === 'development' ) {
        $_SERVER['HTTPS'] = 'on';
    }
} );
```

You'll probably still have to coerce whatever client you're using into making its requests over plain HTTP. The CAS protocol was designed with HTTPS in mind, and client implementations will check for that.
